home = "https://www.notion.so/Social-Media-299e1ed8f1ef8088b224e4efef3e6bcb?source=copy_link"
about = "https://www.notion.so/About-Me-299e1ed8f1ef807ba665c9ad9939b037?source=copy_link"
projects = "https://www.notion.so/Social-Media-299e1ed8f1ef8088b224e4efef3e6bcb?source=copy_link"
contact = "https://www.notion.so/Social-Media-299e1ed8f1ef8088b224e4efef3e6bcb?source=copy_link"
 
